/* ═══════════════════════════════════════════════════════════════════
   DAZURA SEMANTIC DICTIONARY v2.0
   ─────────────────────────────────────────────────────────────────
   תחומים: Connectors · Wires · Electronics · Mechanical · Avionics
   שפות: עברית + אנגלית + מק"טים TE / Deutsch / Amphenol / Molex
   קבוצות: ~350 | מונחים: ~2,800
   ─────────────────────────────────────────────────────────────────
   הוסף מונחים בפורמט:
     'מונח': ['מילה1', 'מילה2', 'word3'],
═══════════════════════════════════════════════════════════════════ */

const DAZURA_DICT = {

/* ══ CONNECTORS — General ══ */
'connector':['קונקטור','מחבר','תקע','שקע','plug','socket','receptacle','coupling','coupler','interface','junction','חיבור','כניסה','יציאה'],
'קונקטור':['connector','plug','socket','receptacle','מחבר','תקע','שקע','coupling','coupler','חיבור'],
'מחבר':['connector','plug','socket','receptacle','קונקטור','תקע','שקע','coupler','junction'],
'plug':['תקע','מחבר','קונקטור','connector','socket','male','pin','זכר'],
'socket':['שקע','מחבר','קונקטור','receptacle','female','נקבה','connector'],
'receptacle':['שקע','מחבר','female','נקבה','socket','connector','קונקטור'],
'תקע':['plug','connector','pin','מחבר','קונקטור','male','זכר'],
'שקע':['socket','receptacle','female','נקבה','מחבר','קונקטור'],
'male':['זכר','plug','pin','תקע','מחבר זכר'],'female':['נקבה','socket','receptacle','שקע','מחבר נקבה'],
'זכר':['male','plug','pin','תקע'],'נקבה':['female','socket','receptacle','שקע'],
'coupling':['קישור','חיבור','connector','coupler','coupling nut'],'coupler':['קישור','חיבור','connector','coupling'],
'circular':['עגול','מחבר עגול','circular connector','mil-spec','dt','dtm','ms','round'],
'מחבר עגול':['circular','circular connector','mil-spec','dt','dtm','ms'],
'עגול':['circular','round','circular connector'],
'rectangular':['מלבני','rectangular connector','מחבר מלבני','square'],
'מלבני':['rectangular','rectangular connector'],

/* ══ CONNECTORS — Deutsch ══ */
'deutsch':['dtm','dt','dtp','hdp','hd','connector','מחבר deutsch'],
'dtm':['deutsch','dtm connector','dtm04','dtm06','circular','מחבר deutsch'],
'dt':['deutsch','dt04','dt06','circular','מחבר deutsch'],
'dtp':['deutsch','power','high current','connector'],
'hdp':['deutsch','heavy duty','power connector','hd'],
'dtm04':['deutsch','dtm','4 pin','4p','plug','connector','male'],
'dtm06':['deutsch','dtm','6 pin','6s','socket','connector','female'],
'dtm04-4p':['dtm','4 pin','plug','deutsch','connector','male','4p'],
'dtm04-4s':['dtm','4 pin','socket','deutsch','connector','female','4s'],
'dtm04-6p':['dtm','6 pin','plug','deutsch','connector'],
'dtm04-6s':['dtm','6 pin','socket','deutsch','connector'],
'dtm04-12p':['dtm','12 pin','plug','deutsch'],
'dtm04-12s':['dtm','12 pin','socket','deutsch'],
'dt04-2p':['dt','2 pin','plug','deutsch'],'dt04-3p':['dt','3 pin','plug','deutsch'],
'dt04-4p':['dt','4 pin','plug','deutsch'],'dt04-6p':['dt','6 pin','plug','deutsch'],
'dt06-2s':['dt','2 pin','socket','deutsch'],'dt06-3s':['dt','3 pin','socket','deutsch'],
'dt06-4s':['dt','4 pin','socket','deutsch'],'dt06-6s':['dt','6 pin','socket','deutsch'],

/* ══ CONNECTORS — TE Connectivity / AMP / Tyco ══ */
'te':['te connectivity','tyco','amp','tyco electronics','te conn'],
'te connectivity':['te','tyco','amp','tyco electronics'],
'tyco':['te','amp','te connectivity','tyco electronics'],
'amp':['te','tyco','amphenol','te connectivity','connector'],
'superseal':['te','superseal 1.5','waterproof','sealed connector','אטום'],
'econoseal':['te','econoseal','connector','sealed'],
'metrimate':['te','metrimate','connector'],
'multilock':['te','multilock','connector'],
'mcp':['te','mcp connector','mini car plug'],
'hd10':['te','hd10','heavy duty','circular'],
'certi-crimp':['te','certicrimp','crimp tool','crimping'],

/* ══ CONNECTORS — Amphenol ══ */
'amphenol':['connector','מחבר','circular','military','industrial','amp'],
'pt':['amphenol','pt02','pt06','circular','bayonet'],
'pt02':['amphenol','pt','plug','circular','bayonet'],'pt06':['amphenol','pt','receptacle','circular'],
'ms':['mil-spec','military','circular','ms27473','ms27474','ms3106','ms3102','ms3100'],
'ms27473':['mil-spec','circular','military connector','מחבר צבאי'],
'ms27474':['mil-spec','circular','military connector','מחבר צבאי'],
'ms3106':['mil-spec','circular','military','plug'],'ms3102':['mil-spec','circular','military','receptacle'],
'ms3100':['mil-spec','circular','military'],'ms3116':['mil-spec','circular','military'],
'd38999':['mil-dtl','circular','military','aerospace','מחבר אוויוני','series iii'],
'mil-dtl-38999':['d38999','circular','military','aerospace'],
'mil-c-5015':['ms3100','ms3106','circular','military'],
'mil-c-26482':['miniature','circular','military'],

/* ══ CONNECTORS — Molex ══ */
'molex':['connector','plug','socket','מחבר','mini-fit','micro-fit','kk','sl'],
'mini-fit':['molex','power','connector','plug','socket','5557','5559'],
'micro-fit':['molex','power','connector','small','compact','430','3mm'],
'kk':['molex','kk connector','2.54mm','0.1 inch','connector'],
'sl':['molex','sl connector','2.54mm','connector'],
'micro-clasp':['molex','micro-clasp','small','connector'],

/* ══ CONNECTORS — JST ══ */
'jst':['connector','plug','socket','small','מחבר קטן','ph','xh','gh','sh','zh','nh'],
'ph':['jst','2mm','ph connector','plug'],'xh':['jst','2.5mm','xh connector','plug'],
'gh':['jst','1.25mm','gh connector'],'sh':['jst','1mm','sh connector'],
'zh':['jst','1.5mm','zh connector'],'nh':['jst','2.54mm','nh connector'],
'sm':['jst','sm connector','2.5mm','housing'],

/* ══ CONNECTORS — Other ══ */
'anderson':['powerpole','power connector','high current','battery','אנדרסון'],
'powerpole':['anderson','power connector','high current','30A','45A','75A'],
'xlr':['audio','microphone','connector','3 pin','5 pin','cannon','xlr3','xlr5'],
'd-sub':['db9','db15','db25','db37','serial','parallel','dsub','מחבר D'],
'db9':['d-sub','9 pin','serial','connector','dsub','rs232'],
'db15':['d-sub','15 pin','connector','dsub','vga'],
'db25':['d-sub','25 pin','parallel','connector','dsub'],
'db37':['d-sub','37 pin','connector','dsub'],
'vga':['db15','video','display','connector','15 pin'],
'hdmi':['video','display','connector','audio video'],
'rj45':['ethernet','network','cat5','cat6','lan','connector','8p8c'],
'rj11':['telephone','phone','connector','4 pin','6p4c'],
'bnc':['coax','coaxial','rf','connector','video','50 ohm','75 ohm'],
'sma':['rf','coax','coaxial','antenna','connector','sma male','sma female','2.4ghz'],
'smb':['rf','coax','connector','push-on','antenna'],
'smc':['rf','coax','connector','screw','antenna'],
'tnc':['rf','coax','coaxial','connector','threaded'],
'n-type':['rf','coax','connector','n connector','n male','n female'],
'f-type':['rf','coax','connector','tv','antenna','cable tv'],
'mcx':['rf','coax','connector','mini','antenna'],
'mmcx':['rf','coax','connector','micro mini','antenna'],
'usb':['usb-a','usb-b','usb-c','micro usb','mini usb','connector','usb2','usb3'],
'usb-a':['usb','type-a','connector','host'],'usb-b':['usb','type-b','connector','device'],
'usb-c':['usb','type-c','connector','modern','usb3.1'],'micro-usb':['usb','micro','connector'],
'mini-usb':['usb','mini','connector'],'usb3':['usb','superspeed','blue','connector'],
'lemo':['circular','push-pull','medical','instrument','connector','lemo 00','lemo 0b'],
'hirose':['small','miniature','connector','japanese','hr10','hr30'],
'souriau':['utx','uta','circular','military','connector'],
'glenair':['backshell','military','circular','connector'],
'radiall':['rf','coax','connector','sma','n-type'],
'itt-cannon':['circular','military','connector','cannon','xcd'],
'harting':['han','industrial','rectangular','connector','han 16','han 24'],
'phoenix-contact':['terminal block','industrial','connector','spring','screwless'],
'weidmuller':['terminal block','industrial','connector','spring clamp'],

/* ══ PINS & CONTACTS ══ */
'pin':['פין','מגע','contact','terminal','probe','needle','pin connector'],
'פין':['pin','contact','terminal','מגע','probe'],
'contact':['מגע','פין','terminal','pin','contact element','crimp contact'],
'מגע':['contact','pin','terminal','פין'],
'terminal':['מגע','פין','קצה','lug','contact','terminal block','ring terminal','spade terminal'],
'קצה':['terminal','end','tip','lug','pin'],
'lug':['terminal','lug connector','ring terminal','spade terminal','crimp lug'],
'ring terminal':['lug','ring','terminal','crimp','עגול','eye terminal'],
'spade terminal':['lug','spade','fork','terminal','crimp','blade'],
'butt splice':['splice','joint','לחיצה','crimp','wire joint'],
'splice':['butt splice','joint','חיבור','crimp','inline connector'],
'ferrule':['wire end','ferrule','end sleeve','bootlace','בוש חוט'],
'socket contact':['female contact','socket pin','נקבה מגע'],
'pin contact':['male contact','pin','זכר מגע'],

/* ══ SEALING & WATERPROOFING ══ */
'seal':['איטום','אטם','sealing','gasket','o-ring','waterproof','plug seal','wire seal'],
'sealing':['איטום','seal','waterproof','ip67','ip68','ip69'],
'איטום':['seal','sealing','gasket','o-ring','waterproof','אטם'],
'אטם':['seal','gasket','o-ring','איטום','rubber seal','gasket seal'],
'gasket':['אטם','seal','איטום','o-ring','rubber gasket','face seal'],
'o-ring':['אטם','seal','gasket','rubber','o ring','oring','איטום'],
'waterproof':['עמיד מים','sealed','ip67','ip68','ip69','water resistant','weatherproof'],
'עמיד מים':['waterproof','sealed','ip67','ip68','weatherproof','water resistant'],
'ip67':['waterproof','sealed','עמיד מים','submersible','1 meter'],
'ip68':['waterproof','sealed','עמיד מים','submersible','deep water'],
'ip69':['waterproof','high pressure','wash down','steam clean'],
'ip54':['splash proof','dust resistant','עמיד אבק'],
'ip65':['dust tight','water jet','nema 4','weatherproof'],
'wire seal':['seal','איטום','plug seal','grommet','rubber seal','wire grommet'],
'plug seal':['seal','איטום','dummy','blank','blocker','hole plug'],
'grommet':['אטם','seal','rubber','wire protection','wire grommet','edge grommet'],
'potting':['encapsulation','epoxy','מילוי','waterproof','embedding','casting'],
'cavity plug':['plug seal','dummy','blank','blocker','spare cavity'],

/* ══ LOCKING & RETENTION ══ */
'wedge':['נעילה','wedgelock','lock','נועל','retention','wedge lock'],
'wedgelock':['wedge','נועל','lock','נעילה','retention device','secondary lock'],
'נועל':['wedge','wedgelock','lock','נעילה','retention'],
'נעילה':['lock','locking','wedge','wedgelock','clip','retention','latching','secondary lock'],
'lock':['נעילה','wedge','clip','retention','latch','locking ring'],
'latch':['נעילה','lock','clip','hook','latching mechanism','snap'],
'clip':['קליפס','retention','spring clip','latch','snap clip'],
'קליפס':['clip','spring','retention','latch','snap'],
'backshell':['הגנה','strain relief','back shell','connector protection','cable clamp'],
'strain relief':['הגנה','backshell','cable relief','protection','כבל הגנה'],
'coupling nut':['nut','lock ring','coupling','connector lock','bayonet nut'],
'secondary lock':['wedge','wedgelock','TPA','terminal position assurance'],
'CPA':['connector position assurance','lock','secondary lock','anti vibration'],

/* ══ TOOLS ══ */
'tool':['כלי','כלי עבודה','כלי הכנסה','כלי שליפה','כלי הידוק','hand tool'],
'כלי':['tool','כלי עבודה','instrument','device','כלי יד'],
'כלי עבודה':['tool','hand tool','כלי'],
'crimper':['כלי הידוק','crimp tool','crimping tool','הידוק','ratchet crimper'],
'crimp tool':['crimper','כלי הידוק','הידוק','ratchet'],
'כלי הידוק':['crimper','crimp tool','crimping','הידוק','ratchet crimper'],
'הידוק':['crimp','crimping','crimper','כלי הידוק'],
'crimping':['הידוק','crimp','crimper','terminal attachment','wire termination'],
'insertion tool':['כלי הכנסה','inserter','כלי פין','pin insertion','pin tool'],
'כלי הכנסה':['insertion tool','inserter','pin tool','insertion probe'],
'extraction tool':['כלי שליפה','extractor','removal tool','pin extractor'],
'כלי שליפה':['extraction tool','extractor','removal tool','pin removal'],
'stripper':['כלי הפשטה','wire stripper','קליפן','insulation removal','stripping tool'],
'wire stripper':['stripper','כלי הפשטה','קליפן','insulation removal'],
'כלי הפשטה':['stripper','wire stripper','קליפן','insulation stripper'],
'קליפן':['stripper','wire stripper','כלי הפשטה'],
'torque wrench':['מפתח מומנט','מפתח','wrench','tightening tool','nm wrench'],
'מפתח מומנט':['torque wrench','מפתח','wrench','nm'],
'ratchet':['ראצ\'ט','ratchet wrench','socket wrench','tool'],
'pliers':['צבת','pliers','gripping tool','needle nose','long nose'],
'צבת':['pliers','gripping','tool','כלי','needle nose pliers'],
'heat gun':['מייבש חם','heat gun','shrink tool','shrink tubing tool'],
'מייבש חם':['heat gun','hot air','shrink tool'],
'soldering iron':['מלחם','soldering','iron','solder tool'],
'מלחם':['soldering iron','solder','soldering'],

/* ══ WIRES & CABLES ══ */
'wire':['חוט','כבל','lead','conductor','חוטים','electric wire'],
'חוט':['wire','cable','lead','conductor','כבל'],
'cable':['כבל','חוט','harness','bundle','loom','wire','cable assembly'],
'כבל':['cable','wire','harness','bundle','חוט'],
'harness':['כבל','wiring harness','wire bundle','loom','צרור חוטים','cable harness'],
'wiring harness':['harness','כבל','wire bundle','loom','cable assembly'],
'צרור חוטים':['harness','wire bundle','cable','wiring','cable loom'],
'loom':['harness','sleeve','protection','כבל','wire bundle','braided sleeving'],
'conductor':['מוליך','wire','lead','חוט','electrical conductor'],
'מוליך':['conductor','wire','lead','חוט'],
'awg':['gauge','wire size','עובי חוט','cross section','חתך','american wire gauge'],
'gauge':['awg','wire size','עובי','thickness','cross section'],
'עובי חוט':['awg','gauge','wire size','cross section','mm2'],
'חתך':['cross section','awg','gauge','area','mm²','mm2'],
'mm²':['cross section','awg','gauge','area','square mm'],
'mm2':['cross section','awg','gauge','area','mm²','square mm'],
'18awg':['18 gauge','18awg','0.75mm²','0.75mm2','wire 18'],
'20awg':['20 gauge','20awg','0.5mm²','0.5mm2','wire 20'],
'22awg':['22 gauge','22awg','0.35mm²','0.35mm2','wire 22'],
'24awg':['24 gauge','24awg','0.22mm²','0.22mm2','wire 24'],
'26awg':['26 gauge','26awg','0.14mm²','wire 26'],
'28awg':['28 gauge','28awg','0.08mm²','wire 28'],
'0.5mm':['0.5mm²','20awg','wire size','cross section'],
'0.75mm':['0.75mm²','18awg','wire size','cross section'],
'1mm':['1mm²','17awg','wire size','cross section'],
'1.5mm':['1.5mm²','15awg','16awg','wire size'],
'2.5mm':['2.5mm²','13awg','14awg','wire size'],
'4mm':['4mm²','11awg','12awg','wire size'],
'6mm':['6mm²','10awg','wire size'],
'shielded':['מוגן','shielded cable','מסוכך','electromagnetic','emi','rfi','screened'],
'מסוכך':['shielded','shielded cable','מוגן','emi','rfi','screened cable'],
'screened':['shielded','מסוכך','emi','screened cable'],
'coaxial':['coax','קואקסיאל','rf','shielded','bnc','sma','rg'],
'קואקסיאל':['coaxial','coax','rf','shielded','קואקסיאל'],
'coax':['coaxial','rf cable','bnc','sma','rg58','rg174','rg316'],
'rg58':['coax','50 ohm','coaxial','antenna cable'],
'rg174':['coax','50 ohm','thin','coaxial'],'rg316':['coax','50 ohm','ptfe','coaxial'],
'twisted pair':['זוג שזור','twisted','differential','ethernet','cat5','cat6'],
'זוג שזור':['twisted pair','twisted','differential','ethernet'],
'ptfe':['teflon','טפלון','wire insulation','high temp','fluoropolymer','m27500'],
'teflon':['ptfe','טפלון','insulation','high temp','fluoropolymer'],
'טפלון':['ptfe','teflon','insulation','high temperature'],
'silicone':['סיליקון','flexible','high temp','insulation','silicone wire'],
'סיליקון':['silicone','flexible','insulation','גמיש'],
'pvc':['pvc insulation','plastic','wire coating','insulation','vinyl'],
'kapton':['polyimide','high temp','flexible','insulation','aerospace','du pont'],
'tefzel':['etfe','wire insulation','aerospace','m22759'],
'xlpe':['cross linked','xlpe','wire insulation','high voltage'],
'spec44':['spec 44','raychem','wire','aerospace','m22759'],
'm22759':['spec44','mil-w','aerospace wire','ptfe','tefzel'],
'm27500':['shielded cable','mil-c','aerospace','shielded'],
'raychem':['spec44','wire','aerospace','heat shrink'],

/* ══ HEAT SHRINK ══ */
'heat shrink':['גלישה חום','shrink tubing','כיווץ חום','shrink tube','heat tube'],
'גלישה חום':['heat shrink','shrink tubing','כיווץ חום'],
'shrink tubing':['heat shrink','גלישה חום','כיווץ חום','tubing'],
'כיווץ חום':['heat shrink','shrink tubing','גלישה חום'],
'2:1':['heat shrink','shrink ratio','2:1 ratio'],
'3:1':['heat shrink','shrink ratio','3:1 ratio','adhesive lined'],
'4:1':['heat shrink','shrink ratio','4:1 ratio','heavy wall'],
'adhesive':['דבק','glue','adhesive lined','bonded','epoxy'],
'dual wall':['adhesive lined','heat shrink','3:1','4:1','waterproof shrink'],

/* ══ EMI & SHIELDING ══ */
'emi':['electromagnetic interference','הגנה','shielding','מסוכך','rfi','emcd'],
'rfi':['radio frequency interference','emi','shielding','הגנה'],
'shielding':['מסוכך','shield','emi','rfi','הגנה אלקטרומגנטית','screening'],
'shield':['מגן','shielding','emi','protective','ground plane'],
'ferrite':['פריט','emi filter','choke','noise suppression','bead','ferrite bead'],
'filter':['מסנן','emi','noise','ferrite','suppressor'],
'מסנן':['filter','emi','noise','suppression','ferrite'],
'bonding':['bonding strap','ground','אדמה','electrical bonding','earth bonding'],
'grounding':['אדמה','ground','bonding','gnd','earth','earthing'],
'drain wire':['שיט','drain','shield ground','emi','coax shield'],
'braid':['mesh','shielding','braided','copper braid','שיט'],

/* ══ ELECTRONICS ══ */
'resistor':['נגד','resistance','ohm','R','נגד חשמלי','fixed resistor'],
'נגד':['resistor','resistance','ohm','R','potentiometer'],
'capacitor':['קבל','capacitance','farad','C','אלקטרוליטי','cap'],
'קבל':['capacitor','capacitance','farad','C','electrolytic'],
'inductor':['סליל','inductance','henry','L','coil','choke'],
'סליל':['inductor','coil','inductance','henry','L','choke coil'],
'diode':['דיודה','rectifier','zener','schottky','LED','TVS'],
'דיודה':['diode','rectifier','LED','zener','schottky'],
'transistor':['טרנזיסטור','transistor','bjt','mosfet','switch','FET'],
'טרנזיסטור':['transistor','bjt','mosfet','switch','FET'],
'relay':['ממסר','relay','switch','coil','contact','solid state relay'],
'ממסר':['relay','switch','coil','contact','power relay'],
'fuse':['פיוז','fuse','protection','overcurrent','circuit breaker','slow blow','fast blow'],
'פיוז':['fuse','protection','overcurrent','blow fuse','slow blow'],
'circuit breaker':['מפסק','breaker','protection','fuse','MCB','thermal breaker'],
'מפסק':['circuit breaker','breaker','switch','relay','MCB'],
'switch':['מתג','switch','toggle','button','relay','SPST','SPDT','DPDT'],
'מתג':['switch','toggle','button','relay','SPDT','DPST'],
'pcb':['לוח','printed circuit board','circuit board','board','PWB'],
'לוח':['pcb','board','circuit board','printed circuit','PCB assembly'],
'ic':['chip','integrated circuit','microchip','שבב','IC chip'],
'chip':['ic','שבב','integrated circuit','microchip','component'],
'שבב':['chip','ic','integrated circuit','microchip'],
'sensor':['חיישן','detector','transducer','probe','sensing'],
'חיישן':['sensor','detector','transducer','sensing element'],
'actuator':['מפעיל','solenoid','motor','servo','driver'],
'מפעיל':['actuator','solenoid','motor','driver'],
'solenoid':['סולנואיד','actuator','coil','valve','electromagnet'],
'סולנואיד':['solenoid','coil','actuator','valve','electromagnet'],
'LED':['נורית','light','diode','indicator','LED lamp'],
'נורית':['LED','indicator','lamp','light','pilot light'],
'transformer':['שנאי','transformer','power','isolation','step up','step down'],
'שנאי':['transformer','power transformer','isolation'],
'voltage regulator':['מייצב מתח','regulator','LDO','7805','78xx'],
'מייצב מתח':['voltage regulator','LDO','regulator','stabilizer'],
'oscillator':['מתנד','crystal','oscillator','clock','quartz'],
'מתנד':['oscillator','crystal','clock','quartz oscillator'],
'crystal':['קריסטל','quartz','oscillator','clock crystal','xtal'],

/* ══ POWER ══ */
'voltage':['מתח','volts','vdc','vac','v','electrical potential','volt'],
'מתח':['voltage','volts','vdc','vac','v','power','volt'],
'current':['זרם','ampere','amps','amp','a','electrical current','amperage'],
'זרם':['current','ampere','amps','amp','a','amperage'],
'power':['כוח','מתח','watt','power supply','supply','הספק','electrical power'],
'כוח':['power','watt','הספק','supply','voltage','current','energy'],
'הספק':['power','watt','kw','energy','output power'],
'ground':['אדמה','gnd','grounding','earth','mass','reference'],
'אדמה':['ground','gnd','grounding','earth','reference ground'],
'gnd':['ground','אדמה','grounding','earth','mass'],
'vdc':['dc voltage','voltage','מתח','direct current','dc power'],
'vac':['ac voltage','voltage','מתח','alternating current','ac power'],
'dc':['direct current','vdc','מתח','voltage','battery','DC power'],
'ac':['alternating current','vac','מתח','voltage','mains','AC power'],
'28v':['28 volt','28vdc','aircraft power','military power'],
'28vdc':['28v','aircraft','military','dc power','avionics power'],
'5v':['5 volt','5vdc','usb power','logic power','TTL'],
'12v':['12 volt','12vdc','automotive','car power','lead acid'],
'24v':['24 volt','24vdc','industrial','plc','automation'],
'48v':['48 volt','48vdc','POE','telecom'],
'115v':['115 volt','115vac','ac power','aircraft ac','avionics'],
'220v':['220 volt','220vac','mains','ac power','domestic'],
'400hz':['400 hz','aircraft power','avionics power','military ac'],
'ampere':['זרם','current','amp','amps','A','amperage'],
'amp':['ampere','זרם','current','amps'],
'ohm':['אום','resistance','impedance','R','ohms'],
'watt':['ואט','power','energy','הספק','W'],
'impedance':['עכבה','impedance','ohm','resistance','Z'],
'עכבה':['impedance','ohm','resistance','Z'],
'psu':['power supply','ספק כוח','power','supply unit','SMPS'],
'ספק כוח':['power supply','psu','power','supply'],

/* ══ MECHANICAL ══ */
'bracket':['מדף','bracket','mount','mounting','holder','תומך','support bracket'],
'מדף':['bracket','shelf','mount','holder','support','shelf bracket'],
'mount':['הרכבה','mounting','bracket','fixture','מדף','mounting plate'],
'הרכבה':['mount','mounting','assembly','installation','fitting'],
'screw':['בורג','fastener','bolt','thread','screw bolt'],
'בורג':['screw','bolt','fastener','thread','machine screw'],
'bolt':['בורג','screw','fastener','nut','hex bolt'],
'nut':['אום','nut','fastener','hex','hex nut'],
'אום':['nut','hex nut','coupling','fastener','בורג'],
'washer':['גרוזיה','washer','flat washer','lock washer','spring washer'],
'גרוזיה':['washer','flat washer','gasket','lock washer'],
'rivet':['ריבט','fastener','pop rivet','blind rivet','cherry rivet'],
'ריבט':['rivet','fastener','pop rivet','blind rivet'],
'clamp':['מהדק','clamp','clip','strap','cable clamp'],
'מהדק':['clamp','clip','strap','fastener','cable clamp'],
'cable tie':['קשריון','tie wrap','zip tie','ty-wrap','nylon tie'],
'קשריון':['cable tie','tie wrap','zip tie','ty-wrap','nylon strap'],
'tie wrap':['קשריון','cable tie','zip tie','ty-wrap'],
'zip tie':['קשריון','cable tie','tie wrap','nylon tie'],
'bearing':['מסב','bearing','roller','ball bearing','sleeve bearing'],
'מסב':['bearing','roller bearing','ball bearing','plain bearing'],
'bushing':['שרוול','bushing','sleeve','liner','plain bearing'],
'spring':['קפיץ','spring','elastic','tension','compression spring'],
'קפיץ':['spring','elastic','tension','coil spring','compression'],
'hinge':['ציר','hinge','pivot','joint','door hinge'],
'ציר':['hinge','axis','pivot','shaft','axle'],
'flange':['פלנג','flange','collar','rim','mounting flange'],
'פלנג':['flange','collar','rim','fitting','pipe flange'],
'fitting':['מחבר','fitting','connector','pipe fitting','union','elbow','tee'],
'union':['חיבור','union','fitting','connector','pipe union'],
'elbow':['מרפק','elbow','90 degree','bend','fitting','L fitting'],
'מרפק':['elbow','90 degree','bend','fitting','L-shaped'],
'tee':['T-fitting','tee','branch','three-way','T connector'],
'panel':['פנל','panel','plate','chassis','mounting panel'],
'פנל':['panel','plate','chassis','front panel'],
'chassis':['שלדה','chassis','frame','enclosure','housing'],
'שלדה':['chassis','frame','enclosure','structure'],
'rack':['מדף רכבה','rack','19 inch','equipment rack','DIN rail'],
'din rail':['din','rail','mounting rail','35mm','omega rail'],

/* ══ AVIONICS & MILITARY ══ */
'avionics':['אוויוניקה','aviation electronics','aircraft','flight systems'],
'אוויוניקה':['avionics','aviation','aircraft','flight','aerospace'],
'aircraft':['מטוס','aviation','avionics','aerospace','aerial','airplane'],
'מטוס':['aircraft','aviation','airplane','aerospace','jet'],
'aerospace':['אוויוניקה','aviation','space','military','aircraft','aero'],
'mil-spec':['military','מפרט צבאי','mil-dtl','mil-std','circular','MS'],
'מפרט צבאי':['mil-spec','military standard','mil-std','spec'],
'mil-std':['military standard','mil-spec','MIL-STD','standard'],
'do-160':['do160','aviation standard','environmental','RTCA','test standard'],
'arinc':['avionics','bus','standard','arinc 429','arinc 629','arinc 664'],
'arinc 429':['arinc429','avionics','data bus','aircraft','label'],
'can bus':['canbus','can','vehicle bus','j1939','automotive bus','SAE'],
'j1939':['can bus','truck','heavy vehicle','SAE J1939'],
'rs-232':['serial','uart','com port','interface','db9'],
'rs-485':['serial','differential','industrial','modbus','interface'],
'rs-422':['serial','differential','avionics','data bus'],
'milcan':['can bus','military','avionics','vehicle'],
'ethernet':['rj45','lan','network','tcp/ip','100base','gigabit'],
'fiber optic':['סיב אופטי','optical fiber','fiber','FOC','fibre'],
'סיב אופטי':['fiber optic','optical','light','fiber','FOC'],
'lru':['line replaceable unit','avionics box','unit','module','black box'],
'antenna':['אנטנה','aerial','rf','transmit','receive','aerial'],
'אנטנה':['antenna','aerial','rf','transmit','receiver'],
'transponder':['מענה','transponder','squawk','aircraft','iff','atc'],
'pitot':['pitot tube','air speed','pressure','sensor','airspeed'],
'hydraulic':['הידראולי','fluid','pressure','pump','hydraulic line'],
'הידראולי':['hydraulic','fluid','pressure','pump','hydraulic system'],
'pneumatic':['פניאומטי','air','pressure','air system','compressed air'],
'פניאומטי':['pneumatic','air pressure','compressed air','air system'],
'iff':['identification','friend','foe','transponder','military','interrogator'],
'atc':['air traffic','transponder','aviation','radar'],
'tcas':['collision avoidance','traffic alert','aviation','safety'],
'gpws':['ground proximity','warning','aviation','safety'],
'fddr':['flight data recorder','black box','avionics'],
'cvr':['cockpit voice recorder','black box','aviation'],

/* ══ MATERIALS ══ */
'aluminum':['אלומיניום','aluminium','al','metal','light','alloy'],
'אלומיניום':['aluminum','aluminium','al','metal','light metal'],
'stainless':['אל חלד','stainless steel','ss','corrosion resistant','304','316'],
'אל חלד':['stainless','stainless steel','ss','rust proof','corrosion free'],
'steel':['פלדה','steel','iron','metal','stainless','carbon steel'],
'פלדה':['steel','iron','metal','carbon steel'],
'titanium':['טיטניום','ti','light','strong','aerospace','grade 5'],
'טיטניום':['titanium','ti','light metal','aerospace material'],
'copper':['נחושת','copper','cu','conductor','electrical conductor'],
'נחושת':['copper','cu','conductor','metal','electrical'],
'brass':['פליז','brass','copper alloy','yellow metal'],
'פליז':['brass','copper alloy','yellow metal','CuZn'],
'rubber':['גומי','rubber','elastomer','seal','flexible','EPDM','Neoprene'],
'גומי':['rubber','elastomer','seal','flexible','synthetic rubber'],
'nylon':['ניילון','nylon','plastic','polyamide','PA66','PA6'],
'ניילון':['nylon','polyamide','plastic','PA66'],
'polyurethane':['פוליאוריטן','pu','flexible','coating','PU'],
'epoxy':['אפוקסי','resin','adhesive','potting','glue','two-part'],
'אפוקסי':['epoxy','resin','adhesive','glue','two-component'],
'peek':['peek','high performance','plastic','aerospace','high temp plastic'],
'delrin':['acetal','delrin','pom','plastic','engineering plastic'],
'ultem':['PEI','high temp','plastic','amber','engineering plastic'],
'inconel':['nickel alloy','high temp','aerospace','superalloy'],
'kovar':['sealing','glass to metal','electronic packaging'],
'gold':['זהב','gold plated','Au','plating','contact plating'],
'זהב':['gold','gold plated','Au','plating'],
'silver':['כסף','silver plated','Ag','plating','conductive'],
'nickel':['ניקל','nickel plated','Ni','plating','corrosion'],
'tin':['בדיל','tin plated','Sn','plating','solder'],

/* ══ STANDARDS ══ */
'rohs':['lead free','environmental','compliance','directive','EU directive'],
'ce':['european','compliance','certification','EU mark'],
'ul':['ul listed','safety','certification','underwriters','UL94'],
'itar':['export control','military','restricted','US export'],
'as9100':['aerospace quality','quality management','aviation quality'],
'iso9001':['quality','ISO','quality system','certification'],
'nadcap':['aerospace','special process','certification','heat treat'],
'sae':['automotive','standard','aerospace','SAE international'],
'iso':['standard','international','quality','ISO standard'],
'ansi':['american','standard','national','ANSI standard'],
'iec':['international','electrotechnical','IEC standard','electrical'],
'nema':['enclosure','rating','IP rating','US standard'],
'rtca':['do-160','aviation','standard','FAA','testing'],

/* ══ COLORS ══ */
'grey':['gray','אפור','silver','light grey','dark grey','slate'],
'gray':['grey','אפור','silver','light gray','dark gray'],
'אפור':['grey','gray','silver','charcoal'],
'black':['שחור','noir','dark','BLK'],
'שחור':['black','dark','noir','BLK'],
'white':['לבן','blanc','WHT','ivory'],
'לבן':['white','ivory','WHT','off-white'],
'red':['אדום','rouge','RED'],
'אדום':['red','rouge','RED'],
'blue':['כחול','bleu','BLU'],
'כחול':['blue','bleu','BLU','navy'],
'green':['ירוק','GRN','lime'],
'ירוק':['green','GRN','lime green'],
'yellow':['צהוב','YEL','amber','gold'],
'צהוב':['yellow','YEL','amber'],
'orange':['כתום','ORG','amber'],
'כתום':['orange','ORG'],
'brown':['חום','BRN'],
'חום':['brown','BRN','tan'],
'violet':['סגול','purple','VIO'],
'סגול':['violet','purple','VIO'],
'pink':['ורוד','PNK'],
'ורוד':['pink','PNK','rose'],
'silver':['כסוף','silver grey','metallic','אפור'],
'כסוף':['silver','metallic','silver grey'],
'natural':['טבעי','natural color','translucent','clear'],
'transparent':['שקוף','clear','transparent','translucent'],
'שקוף':['transparent','clear','translucent'],

/* ══ DIMENSIONS ══ */
'2 pin':['2p','2 way','2 position','dual','2-pin'],
'3 pin':['3p','3 way','3 position','triple','3-pin'],
'4 pin':['4p','4 way','4 position','quad','4-pin'],
'6 pin':['6p','6 way','6 position','6-pin'],
'8 pin':['8p','8 way','8 position','8-pin'],
'9 pin':['9p','9 way','db9','9-pin'],
'12 pin':['12p','12 way','12 position','12-pin'],
'16 pin':['16p','16 way','16 position','16-pin'],
'24 pin':['24p','24 way','24 position','24-pin'],
'2p':['2 pin','2 way','2 position'],'3p':['3 pin','3 way','3 position'],
'4p':['4 pin','4 way','4 position'],'6p':['6 pin','6 way','6 position'],
'8p':['8 pin','8 way','8 position'],'12p':['12 pin','12 way','12 position'],
'4s':['4 socket','4 pin female','4 way socket'],
'6s':['6 socket','6 pin female','6 way socket'],

/* ══ PROCESS ══ */
'install':['התקנה','הרכבה','install','assembly','mount','mounting'],
'התקנה':['install','assembly','mounting','הרכבה','installation'],
'assembly':['הרכבה','assembly','kit','installation','build'],
'הרכבה':['assembly','installation','install','mount','assy'],
'repair':['תיקון','repair','fix','maintenance','rework','refurbish'],
'תיקון':['repair','fix','maintenance','rework'],
'maintenance':['תחזוקה','maintenance','service','upkeep','overhaul'],
'תחזוקה':['maintenance','service','repair','overhaul','PM'],
'inspection':['בדיקה','inspection','check','verify','QA','QC'],
'בדיקה':['test','inspection','check','verify','testing'],
'test':['בדיקה','test','inspection','check','verify','testing'],
'torque':['מומנט','torque','tightening','nm','ft-lb','in-lb'],
'מומנט':['torque','tightening','nm','force','torque spec'],
'calibration':['כיול','calibration','cal','adjustment','tuning'],
'כיול':['calibration','cal','adjustment'],

/* ══ CHARACTERISTICS ══ */
'high temperature':['טמפרטורה גבוהה','high temp','heat resistant','high heat'],
'טמפרטורה גבוהה':['high temperature','high temp','heat','thermal'],
'vibration':['רטט','vibration','shock','mechanical stress','vibration resistant'],
'רטט':['vibration','shock','vibration resistant','anti-vibration'],
'flexible':['גמיש','flexible','flex','bending','pliable'],
'גמיש':['flexible','flex','soft','bending','pliable'],
'rigid':['נוקשה','rigid','stiff','hard','inflexible'],
'compact':['קומפקטי','compact','small','miniature','tiny','low profile'],
'lightweight':['קל משקל','light','lightweight','low weight','low mass'],
'קל משקל':['lightweight','light','low mass','light weight'],
'miniature':['מיניאטורי','mini','small','compact','tiny','micro'],
'מיניאטורי':['miniature','mini','micro','small','compact'],
'heavy duty':['עמיד','robust','rugged','industrial','heavy','כבד'],
'rugged':['עמיד','rugged','robust','military grade','heavy duty','harsh'],
'עמיד':['rugged','robust','heavy duty','durable','reliable'],
'high current':['זרם גבוה','high amperage','power connector','heavy current'],
'זרם גבוה':['high current','high amperage','power','heavy duty'],
'high voltage':['מתח גבוה','HV','high volt'],
'מתח גבוה':['high voltage','HV'],
'low profile':['שטוח','low profile','flat','slim','thin connector'],
'שטוח':['low profile','flat','slim','thin'],
'surface mount':['SMD','SMT','surface mount','chip component'],
'through hole':['through hole','DIP','PCB through','axial'],
};

function dazuraExpand(query){
  const tokens=String(query||'').toLowerCase()
    .replace(/[^\w\u0590-\u05ff\s]/g,' ')
    .split(/\s+/).filter(w=>w.length>1);
  const all=new Set(tokens);
  tokens.forEach(t=>{
    if(DAZURA_DICT[t])DAZURA_DICT[t].forEach(s=>all.add(s.toLowerCase()));
    Object.keys(DAZURA_DICT).forEach(key=>{
      if(key.length>=3&&t.length>=3&&(key.startsWith(t)||t.startsWith(key))){
        all.add(key);
        DAZURA_DICT[key].forEach(s=>all.add(s.toLowerCase()));
      }
    });
  });
  return[...all];
}

function dazuraScore(query,itemText){
  const expanded=dazuraExpand(query);
  const text=itemText.toLowerCase();
  let score=0;
  expanded.forEach(term=>{
    if(term.length<2)return;
    if(text.includes(term))score+=Math.min(40,term.length*4);
  });
  return Math.min(score,100);
}

if(typeof window!=='undefined')window._dazuraSemanticsLoaded=true;
